Add support for Corrade commands attach, detach, pay avatar, pay object, create landmark and notecard, get balance, key2name, name2key, wear, unwear

diff --git a/LifeBots/bin/send_bot_balance b/LifeBots/bin/send_bot_balance
--- a/LifeBots/bin/send_bot_balance
+++ b/LifeBots/bin/send_bot_balance
@@ -7,9 +7,12 @@
 # Set this to your Second Life avatar name
 DEF_SL_NAME="Missy Restless"
 # Set this to your bot's name
-DEF_BOT_NAME="Easy Islay"
+DEF_BOT_NAME="Easy"
 # Set this to all your bots names or their aliases, for use with -A
-ALL_BOTS="Angel Anya Easy"
+ALL_LB_BOTS="Anya"
+ALL_CO_BOTS="Angel Easy"
+ALL_BOTS="${ALL_LB_BOTS} ${ALL_CO_BOTS}"
+CORRADE=
 
 export PATH="/usr/local/bin:${PATH}"
 [ -d /opt/homebrew/bin ] && {
@@ -39,24 +42,56 @@ usage() {
 }
 
 send_balance() {
+  local bot_type="$1"
+  local bot_arg="-n"
+  local BALANCE=0
+
+  CORRADE=
+  if [ "${bot_type}" == "-c" ]; then
+    bot_arg="-c"
+    CORRADE=1
+  else
+    if [ "${bot_type}" == "-l" ]; then
+      bot_arg="-n"
+      CORRADE=
+    else
+      echo "${ALL_LB_BOTS}" | grep "${BOT_NAME}" >/dev/null || {
+        bot_arg="-c"
+        CORRADE=1
+        echo "${ALL_CO_BOTS}" | grep "${BOT_NAME}" >/dev/null || {
+          echo "Unable to determine bot type. Unknown bot."
+          exit 1
+        }
+      }
+    fi
+  fi
   # Get the bot's balance
   [ "${debug}" ] && {
     echo "Getting bot balance with:"
-    echo "lifebot -a balance -n \"${BOT_NAME}\" | jq -r '.balance'"
+    if [ "${CORRADE}" ]; then
+      echo "lifebot -a balance ${bot_arg} \"${BOT_NAME}\" | jq -r '.data[0]'"
+    else
+      echo "lifebot -a balance ${bot_arg} \"${BOT_NAME}\" | jq -r '.balance'"
+    fi
   }
-  BALANCE=$(lifebot -a balance -n "${BOT_NAME}" | jq -r '.balance')
+  if [ "${CORRADE}" ]; then
+    BALANCE=$(lifebot -a balance ${bot_arg} "${BOT_NAME}" | jq -r '.data[0]')
+  else
+    BALANCE=$(lifebot -a balance ${bot_arg} "${BOT_NAME}" | jq -r '.balance')
+  fi
   [ "${BALANCE}" ] || {
     echo "ERROR: cannot get bot ${BOT_NAME} balance"
     exit 1
   }
 
   # Send balance if it is greater than 0
+  [ "${debug}" ] && echo "Balance = ${BALANCE}"
   [ ${BALANCE} -gt 0 ] && {
     [ "${debug}" ] && {
       echo "Sending bot balance to ${SL_NAME} with:"
-      echo "lifebot -a give_money -n \"${BOT_NAME}\" -u \"${SL_UUID}\" -z ${BALANCE} ${debug}"
+      echo "lifebot -a give_money ${bot_arg} \"${BOT_NAME}\" -A \"${SL_UUID}\" -z ${BALANCE} ${debug}"
     }
-    lifebot -a give_money -n "${BOT_NAME}" -u "${SL_UUID}" -z ${BALANCE} ${debug}
+    lifebot -a give_money ${bot_arg} "${BOT_NAME}" -A "${SL_UUID}" -z ${BALANCE} ${debug}
   }
 }
 
@@ -91,22 +126,48 @@ shift $(( OPTIND - 1 ))
 [ "${BOT_NAME}" ] || BOT_NAME="${DEF_BOT_NAME}"
 [ "${SL_NAME}" ] || SL_NAME="${DEF_SL_NAME}"
 
-SL_UUID=$(lifebot -a name2key -n "${BOT_NAME}" -N "${SL_NAME}" | jq -r '.key') 
+CORRADE=
+echo "${ALL_LB_BOTS}" | grep "${BOT_NAME}" >/dev/null || {
+  CORRADE=1
+  echo "${ALL_CO_BOTS}" | grep "${BOT_NAME}" >/dev/null || {
+    echo "Unable to determine bot type. Unknown bot."
+    exit 1
+  }
+}
+
+if [ "${CORRADE}" ]; then
+  SL_UUID=$(lifebot -a name2key -c "${BOT_NAME}" -N "${SL_NAME}" | jq -r '.data[1]')
+else
+  SL_UUID=$(lifebot -a name2key -n "${BOT_NAME}" -N "${SL_NAME}" | jq -r '.key') 
+fi
 [ "${SL_UUID}" ] || {
   echo "ERROR: cannot get UUID for Second Life avatar name ${SL_NAME}"
   exit 1
 }
 
 if [ "${allbots}" ]; then
-  for bot in ${ALL_BOTS}
-  do
-    BOT_NAME="${bot}"
-    [ "${BOT_NAME}" ] || {
-      echo "ERROR: empty bot name"
-      exit 1
-    }
-    send_balance
-  done
+  [ "${ALL_LB_BOTS}" ] && {
+    for bot in ${ALL_LB_BOTS}
+    do
+      BOT_NAME="${bot}"
+      [ "${BOT_NAME}" ] || {
+        echo "ERROR: empty bot name"
+        exit 1
+      }
+      send_balance -l
+    done
+  }
+  [ "${ALL_CO_BOTS}" ] && {
+    for bot in ${ALL_CO_BOTS}
+    do
+      BOT_NAME="${bot}"
+      [ "${BOT_NAME}" ] || {
+        echo "ERROR: empty bot name"
+        exit 1
+      }
+      send_balance -c
+    done
+  }
 else
   [ "${BOT_NAME}" ] || {
     echo "ERROR: empty bot name"
